# Generated by Django 3.0.7 on 2021-03-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopan', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='intel',
            new_name='School',
        ),
    ]
