# Generated by Django 3.0.7 on 2021-03-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopan', '0002_auto_20210325_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School',
            new_name='Sup',
        ),
    ]
