# Generated by Django 3.0.7 on 2021-03-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopan', '0003_auto_20210325_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sup',
            new_name='Html',
        ),
    ]
