# Generated by Django 3.0.7 on 2021-03-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sopan', '0004_auto_20210325_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Html',
            new_name='intel',
        ),
    ]
