# Generated by Django 3.0.7 on 2021-06-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sopan', '0005_auto_20210325_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='save',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
